In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise_distances

In [2]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [3]:
import pandas as pd

mynta = pd.read_csv("/gdrive/My Drive/dataset-ml/mynta.csv",encoding="Latin1")
Ratings = pd.read_csv("/gdrive/My Drive/dataset-ml/mynta-rating.csv")

Mean = Ratings.groupby(by="userId",as_index=False)['rating'].mean()
Rating_mean = pd.merge(Ratings,Mean,on='userId')
Rating_mean['adg_rating']=Rating_mean['rating_x']-Rating_mean['rating_y']
Rating_mean

      userId  titleId  rating_x  rating_y  adg_rating
0      12882        1       4.0  4.061321   -0.061321
1      12882       32       3.5  4.061321   -0.561321
2      12882       47       5.0  4.061321    0.938679
3      12882       50       5.0  4.061321    0.938679
4      12882      110       4.5  4.061321    0.438679
...      ...      ...       ...       ...         ...
2495    8932    53125       3.5  3.569532   -0.069532
2496    8932    53322       3.0  3.569532   -0.569532
2497    8932    53519       4.0  3.569532    0.430468
2498    8932    53894       3.5  3.569532   -0.069532
2499    8932    53953       1.0  3.569532   -2.569532

[2500 rows x 5 columns]

In [4]:
mynta

      titleId                                       title  ... price  discount
0           1                  Printed Round Neck T-Shirt  ...   699        5%
1           2                          Solid Polo T-shirt  ...   799       50%
2           3            Colourblocked Round Neck T-shirt  ...   699       35%
3           4               Camouflage Round Neck T-shirt  ...   699       35%
4           5  Colourblocked Round Neck Navy Blue T-shirt  ...   899       50%
...       ...                                         ...  ...   ...       ...
2495   109487                   Solid Slub Jersey T-shirt  ...   799        0%
2496   111362                   Striped Yarn Dyed T-shirt  ...  1099       60%
2497   111759                 Striped Polo Collar T-shirt  ...   999       21%
2498   112556                 Printed Polo Collar T-shirt  ...  1299       60%
2499   112852                 Striped Polo Collar T-shirt  ...  1199       50%

[2500 rows x 6 columns]

In [5]:
Ratings

      userId  titleId  rating
0      12882        1     4.0
1      12882       32     3.5
2      12882       47     5.0
3      12882       50     5.0
4      12882      110     4.5
...      ...      ...     ...
2495    8932    53125     3.5
2496    8932    53322     3.0
2497    8932    53519     4.0
2498    8932    53894     3.5
2499    8932    53953     1.0

[2500 rows x 3 columns]

In [6]:
check = pd.pivot_table(Rating_mean,values='rating_x',index='userId',columns='titleId')
check

titleId  1       2       5       6       ...  106489  111362  111759  112852
userId                                   ...
320         NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
8932        4.0     NaN     2.0     5.0  ...     NaN     NaN     NaN     NaN
12882       4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
17318       4.0     4.0     NaN     3.0  ...     NaN     NaN     NaN     NaN
18127       4.0     NaN     NaN     4.0  ...     NaN     NaN     NaN     NaN
62046       NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
69519       4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
103754      NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
115611      NaN     NaN     NaN     3.0  ...     4.0     NaN     NaN     NaN
121987      4.5     NaN     NaN     NaN  ...     NaN     4.5     4.5     4.5
124823      4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[11 rows x 1270 columns]

In [7]:
final = pd.pivot_table(Rating_mean,values='adg_rating',index='userId',columns='titleId')
final

titleId    1        2         5       ...    111362    111759    112852
userId                                ...
320           NaN      NaN       NaN  ...       NaN       NaN       NaN
8932     0.430468      NaN -1.569532  ...       NaN       NaN       NaN
12882   -0.061321      NaN       NaN  ...       NaN       NaN       NaN
17318   -0.030120 -0.03012       NaN  ...       NaN       NaN       NaN
18127    0.381378      NaN       NaN  ...       NaN       NaN       NaN
62046         NaN      NaN       NaN  ...       NaN       NaN       NaN
69519    0.345133      NaN       NaN  ...       NaN       NaN       NaN
103754        NaN      NaN       NaN  ...       NaN       NaN       NaN
115611        NaN      NaN       NaN  ...       NaN       NaN       NaN
121987   0.327778      NaN       NaN  ...  0.327778  0.327778  0.327778
124823   0.335616      NaN       NaN  ...       NaN       NaN       NaN

[11 rows x 1270 columns]

In [8]:
final_mynta = final.fillna(final.mean(axis=0))

final_user = final.apply(lambda row: row.fillna(row.mean()), axis=1)

In [9]:
final_mynta

titleId    1        2         5       ...    111362    111759    112852
userId                                ...
320      0.246990 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
8932     0.430468 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
12882   -0.061321 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
17318   -0.030120 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
18127    0.381378 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
62046    0.246990 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
69519    0.345133 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
103754   0.246990 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
115611   0.246990 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
121987   0.327778 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778
124823   0.335616 -0.03012 -1.569532  ...  0.327778  0.327778  0.327778

[11 rows x 1270 columns]

In [10]:
final_user

titleId        1             2       ...        111759        112852
userId                               ...
320      4.297638e-17  4.297638e-17  ...  4.297638e-17  4.297638e-17
8932     4.304678e-01 -1.830254e-16  ... -1.830254e-16 -1.830254e-16
12882   -6.132075e-02  4.021940e-16  ...  4.021940e-16  4.021940e-16
17318   -3.012048e-02 -3.012048e-02  ... -3.495642e-16 -3.495642e-16
18127    3.813776e-01 -2.752900e-16  ... -2.752900e-16 -2.752900e-16
62046   -1.716840e-16 -1.716840e-16  ... -1.716840e-16 -1.716840e-16
69519    3.451327e-01 -1.002148e-16  ... -1.002148e-16 -1.002148e-16
103754  -4.314009e-16 -4.314009e-16  ... -4.314009e-16 -4.314009e-16
115611  -3.307047e-17 -3.307047e-17  ... -3.307047e-17 -3.307047e-17
121987   3.277778e-01 -2.763222e-16  ...  3.277778e-01  3.277778e-01
124823   3.356164e-01 -3.345878e-16  ... -3.345878e-16 -3.345878e-16

[11 rows x 1270 columns]

In [11]:
b = cosine_similarity(final_user)
np.fill_diagonal(b, 0 )
similarity_with_user = pd.DataFrame(b,index=final_user.index)
similarity_with_user.columns=final_user.index
similarity_with_user

userId    320       8932      12882   ...    115611    121987    124823
userId                                ...
320     0.000000  0.064841  0.116732  ...  0.071757  0.082091  0.003486
8932    0.064841  0.000000  0.124823  ...  0.019753  0.038364 -0.058481
12882   0.116732  0.124823  0.000000  ...  0.030732  0.025454 -0.037725
17318   0.122849  0.063221  0.125703  ...  0.093774  0.079104 -0.006067
18127   0.075886  0.111153  0.134325  ...  0.048165  0.093262  0.052343
62046   0.041275  0.094324  0.127677  ...  0.100314  0.050331 -0.057753
69519   0.045473  0.097935  0.101994  ...  0.017787  0.026295  0.020660
103754  0.036896  0.071889  0.063578  ...  0.049518 -0.024545 -0.084195
115611  0.071757  0.019753  0.030732  ...  0.000000  0.057900 -0.028553
121987  0.082091  0.038364  0.025454  ...  0.057900  0.000000  0.059371
124823  0.003486 -0.058481 -0.037725  ... -0.028553  0.059371  0.000000

[11 rows x 11 columns]

In [12]:
cosine = cosine_similarity(final_mynta)
np.fill_diagonal(cosine, 0 )
similarity_with_mynta = pd.DataFrame(cosine,index=final_mynta.index)
similarity_with_mynta.columns=final_user.index
similarity_with_mynta

userId    320       8932      12882   ...    115611    121987    124823
userId                                ...
320     0.000000  0.905241  0.980652  ...  0.944706  0.987937  0.961683
8932    0.905241  0.000000  0.899670  ...  0.832569  0.909787  0.864113
12882   0.980652  0.899670  0.000000  ...  0.932751  0.982570  0.957279
17318   0.970378  0.878485  0.967175  ...  0.929173  0.973162  0.945938
18127   0.949205  0.831748  0.943696  ...  0.903965  0.948336  0.930565
62046   0.956313  0.866921  0.954483  ...  0.907797  0.958944  0.925434
69519   0.973393  0.887734  0.971254  ...  0.934543  0.977006  0.954008
103754  0.982854  0.903764  0.979023  ...  0.944443  0.984577  0.958257
115611  0.944706  0.832569  0.932751  ...  0.000000  0.946256  0.918126
121987  0.987937  0.909787  0.982570  ...  0.946256  0.000000  0.966035
124823  0.961683  0.864113  0.957279  ...  0.918126  0.966035  0.000000

[11 rows x 11 columns]

In [13]:
def find_n_neighbours(df,n):
    order = np.argsort(df.values, axis=1)[:, :n]
    df = df.apply(lambda x: pd.Series(x.sort_values(ascending=False)
           .iloc[:n].index, 
          index=['top{}'.format(i) for i in range(1, n+1)]), axis=1)
    return df

In [14]:
sim_user_30_u = find_n_neighbours(similarity_with_user,11)
sim_user_30_u

          top1    top2    top3    top4  ...    top8    top9   top10   top11
userId                                  ...
320      17318   12882  121987   18127  ...   62046  103754  124823     320
8932     12882   18127   69519   62046  ...  121987  115611    8932  124823
12882    18127   62046   17318    8932  ...  115611  121987   12882  124823
17318    12882     320  115611  121987  ...   18127   69519   17318  124823
18127    12882    8932  121987     320  ...   17318  115611   18127  103754
62046    12882  115611    8932   17318  ...   69519     320   62046  124823
69519    12882    8932   18127     320  ...  124823  103754  115611   69519
103754    8932   17318   12882   62046  ...  103754   18127  121987  124823
115611   62046   17318     320  121987  ...    8932   69519  115611  124823
121987   18127     320   17318  124823  ...   69519   12882  121987  103754
124823  121987   18127   69519     320  ...   12882   62046    8932  103754

[11 rows x 11 columns]

In [15]:
sim_user_30_m = find_n_neighbours(similarity_with_mynta,11)
sim_user_30_m

          top1    top2    top3   top4  ...    top8    top9  top10   top11
userId                                 ...
320     121987  103754   12882  69519  ...   18127  115611   8932     320
8932    121987     320  103754  12882  ...  124823  115611  18127    8932
12882   121987     320  103754  69519  ...   18127  115611   8932   12882
17318   121987     320  103754  12882  ...   18127  115611   8932   17318
18127      320  121987  103754  12882  ...   62046  115611   8932   18127
62046   121987  103754     320  12882  ...   18127  115611   8932   62046
69519   121987  103754     320  12882  ...  115611   18127   8932   69519
103754  121987     320   12882  69519  ...  115611   18127   8932  103754
115611  121987     320  103754  69519  ...   62046   18127   8932  115611
121987     320  103754   12882  69519  ...   18127  115611   8932  121987
124823  121987     320  103754  12882  ...   62046  115611   8932  124823

[11 rows x 11 columns]

In [16]:
def get_user_similar_mynta( user1, user2 ):
    common_mynta = Rating_mean[Rating_mean.userId == user1].merge(
    Rating_mean[Rating_mean.userId == user2],
    on = "titleId",
    how = "inner" )
    return common_mynta.merge( mynta, on = 'titleId' )

In [29]:

a = get_user_similar_mynta(370,86309)
a = a.loc[ : , ['rating_x_x','rating_x_y','title']]
a

Empty DataFrame
Columns: [rating_x_x, rating_x_y, title]
Index: []

In [18]:
def User_item_score(user,item):
    a = sim_user_30_m[sim_user_30_m.index==user].values
    b = a.squeeze().tolist()
    c = final_mynta.loc[:,item]
    d = c[c.index.isin(b)]
    f = d[d.notnull()]
    mean_user = Mean.loc[Mean['userId'] == user,'rating'].values[0]
    index = f.index.values.squeeze().tolist()
    corr = similarity_with_mynta.loc[user,index]
    fin = pd.concat([f, corr], axis=1)
    fin.columns = ['adg_score','correlation']
    fin['score']=fin.apply(lambda x:x['adg_score'] * x['correlation'],axis=1)
    nume = fin['score'].sum()
    deno = fin['correlation'].sum()
    final_score = mean_user + (nume/deno)
    return final_score

In [28]:
score = User_item_score(320,2571)
print("score (u,i) is",score)

score (u,i) is 3.8172170664127467

In [20]:
Rating_mean = Rating_mean.astype({"titleId": str})
mynta_user = Rating_mean.groupby(by = 'userId')['titleId'].apply(lambda x:','.join(x))

In [21]:
def User_item_score1(user, x_output):
    mynta_seen_by_user = check.columns[check[check.index==user].notna().any()].tolist()
    a = sim_user_30_m[sim_user_30_m.index==user].values
    b = a.squeeze().tolist()
    d = mynta_user[mynta_user.index.isin(b)]
    l = ','.join(d.values)
    mynta_seen_by_similar_users = l.split(',')
    mynta_under_consideration = list(set(mynta_seen_by_similar_users)-set(list(map(str, mynta_seen_by_user))))
    mynta_under_consideration = list(map(int, mynta_under_consideration))
    score = []
    for item in mynta_under_consideration:
        c = final_mynta.loc[:,item]
        d = c[c.index.isin(b)]
        f = d[d.notnull()]
        mean_user = Mean.loc[Mean['userId'] == user,'rating'].values[0]
        index = f.index.values.squeeze().tolist()
        corr = similarity_with_mynta.loc[user,index]
        fin = pd.concat([f, corr], axis=1)
        fin.columns = ['adg_score','correlation']
        fin['score']=fin.apply(lambda x:x['adg_score'] * x['correlation'],axis=1)
        nume = fin['score'].sum()
        deno = fin['correlation'].sum()
        final_score = mean_user + (nume/deno)
        score.append(final_score)
    data = pd.DataFrame({'titleId':mynta_under_consideration,'score':score})
    top_2_recommendation = data.sort_values(by='score',ascending=False).head(2)
    mynta_Name = top_2_recommendation.merge(mynta, how='inner', on='titleId')
    if x_output == 1:
      mynta_Names = mynta_Name.title.values.tolist()
    elif x_output == 2:
      mynta_Names = mynta_Name.brand.values.tolist()
    elif x_output == 3:
      mynta_Names = mynta_Name.price.values.tolist()
    elif x_output == 4:
      mynta_Names = mynta_Name.discount.values.tolist()

    return mynta_Names

In [22]:
user = int(input("Enter the user id to recommend : "))
predicted_mynta_title = User_item_score1(user, 1)
predicted_mynta_brand = User_item_score1(user, 2)
predicted_mynta_price = User_item_score1(user, 3)
predicted_mynta_discount = User_item_score1(user, 4)
print(" ")
print("   ")

for i in range(len(predicted_mynta_title)):
    #output = predicted_mynta_title[i] + " | " + predicted_mynta_brand[i] + " | " + predicted_mynta_price[i] + " | " + predicted_mynta_discount[i]
    print(predicted_mynta_title[i], " | ", predicted_mynta_brand[i], " | ", predicted_mynta_price[i], " | ", predicted_mynta_discount[i])

Enter the user id to recommend : 12882


Men Solid T-shirt  |  United Colors of Benetton  |  1399  |  30%
Printed Hood T-shirt  |  WROGN  |  1299  |  35%